### PR TITLE
Styling/error display

### LINKED ISSUE #20: Error Page - Single Movie <Detail />
**Describe the bug**
If an error occurs when fetching single move data, the error page displays correctly! 
BUT
- Clicking Home: error page does not unmount
- Using back button from error page: Top Five and All Movies do not display

**To Reproduce**
1. Go to 'Detail.js', change the fetch params to break fetch call
2. Go to 'Home Page' 
3. Click on 'an individual movie'
4. See an error, Click 'back' 
5. Repeat 1-3, 'Click Home'

**Expected behavior**
Fiux functionality to display correct movies details when navigating to and from an error message.

**Screenshots**

**Additional context**

### LINKED ISSUE #21: FR - Navbar Component
**What is the feature that you're expecting?**
Refactor App to take a navigation bar component, remove all NavLinks in App.js

**Anticipated Completion Date**
02/13/21

**Additional context**

### PR DESCRIPTION
**Pull request by alia-peterson**
## *Purpose:*
*What does this merge do? Check all that apply.*
- [ ] Adds a new feature
- [x] Improves an existing feature
- [x] Fixes a bug
- [ ] Cleans up (logs, tests, etc.)

## *Description: What does this PR do?*
- Updated the visuals for the error page
- Added an errorMessage state to app to handle an incorrect ID path/url
- Added an error state to App so that one condition could be checked for multiple types of errors

## *What are the relevant tickets?*
Closes #20, closes #21

## *Bugs:*
No known bugs! 🤞🏼

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have used tests to prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change

### CODE REVIEW

File: src/components/App/App.js [hunk 1]
```diff
@@ -45,85 +48,83 @@ class App extends Component {
...
+            resetError={this.resetError}
+          />
+          {this.state.error &&
+            <ErrorMessage
+              status={this.state.errorStatus}
+              message={this.state.errorMessage}
+            />
+          }
+          {this.state.isLoading ? <Loading /> :
+            <>
```
Comment (kevinhartmann23) [inline src/components/App/App.js:105]: - Was switch removed? I'm assuming there is no need now with the change in components. Let's discuss this AM before merging!

**Review by kevinhartmann23 — COMMENTED** [review]
- [x] Changes generate no new warnings or errors
- [x] Branch was tested locally without failures
- [ ] All tests are passing as expected
